
use once_cell::sync::Lazy;
use parking_lot::Mutex;
use smash::lib::lua_const::*;
use std::collections::HashMap;

#[derive(Clone, Copy)]
enum ParamValue {
    Int(i32),
    Float(f32),
}

type ParamKey = (i32, Vec<i32>, u64, u64);

static BASELINES: Lazy<Mutex<HashMap<ParamKey, ParamValue>>> = Lazy::new(|| Mutex::new(HashMap::new()));

pub fn update_float_2(kind: i32, slots: Vec<i32>, param: (u64, u64, f32)) {
    BASELINES.lock().insert((kind, slots.clone(), param.0, param.1), ParamValue::Float(param.2));
    param_config::update_float_2(kind, slots, param);
}

pub fn update_int_2(kind: i32, slots: Vec<i32>, param: (u64, u64, i32)) {
    BASELINES.lock().insert((kind, slots.clone(), param.0, param.1), ParamValue::Int(param.2));
    param_config::update_int_2(kind, slots, param);
}

pub fn update_attribute_mul(kind: i32, slots: Vec<i32>, param: (u64, u64, f32)) {
    let (type_hash, name_hash, multiplier) = param;

    if kind == *FIGHTER_KIND_ALL {
        apply_multiplier_to_all_kinds(slots, type_hash, name_hash, multiplier);
        return;
    }

    let key = (kind, slots.clone(), type_hash, name_hash);
    match BASELINES.lock().get(&key).copied() {
        Some(ParamValue::Float(base)) => {
            let new_value = base * multiplier;
            BASELINES.lock().insert(key, ParamValue::Float(new_value));
            param_config::update_float_2(kind, slots, (type_hash, name_hash, new_value));
        }
        Some(ParamValue::Int(base)) => {
            let new_value = (base as f32 * multiplier).round() as i32;
            BASELINES.lock().insert(key, ParamValue::Int(new_value));
            param_config::update_int_2(kind, slots, (type_hash, name_hash, new_value));
        }
        None => {
            param_config::update_attribute_mul_2(kind, slots, (type_hash, name_hash, multiplier));
        }
    }
}

/// Every base folder name used anywhere in this codebase (get_marked_costumes/
/// get_costume_count/get_lowest_marked_costume calls), paired with its real
/// fighter kind. Mechanically generated by cross-referencing those calls
/// against the full FIGHTER_KIND_* constant list - all 86 matched
/// `FIGHTER_KIND_<FOLDER.upper()>` exactly, so that's the pairing here too.
/// Built once at runtime (not `const`): LuaConst's Deref isn't const, so
/// `*FIGHTER_KIND_X` can't appear in a const/static initializer directly.
static KIND_TO_FOLDER: Lazy<HashMap<i32, &'static str>> = Lazy::new(|| {
    let pairs: &[(&str, i32)] = &[
        ("bayonetta", *FIGHTER_KIND_BAYONETTA),
        ("brave", *FIGHTER_KIND_BRAVE),
        ("buddy", *FIGHTER_KIND_BUDDY),
        ("captain", *FIGHTER_KIND_CAPTAIN),
        ("chrom", *FIGHTER_KIND_CHROM),
        ("cloud", *FIGHTER_KIND_CLOUD),
        ("daisy", *FIGHTER_KIND_DAISY),
        ("dedede", *FIGHTER_KIND_DEDEDE),
        ("demon", *FIGHTER_KIND_DEMON),
        ("diddy", *FIGHTER_KIND_DIDDY),
        ("dolly", *FIGHTER_KIND_DOLLY),
        ("donkey", *FIGHTER_KIND_DONKEY),
        ("duckhunt", *FIGHTER_KIND_DUCKHUNT),
        ("edge", *FIGHTER_KIND_EDGE),
        ("eflame", *FIGHTER_KIND_EFLAME),
        ("elight", *FIGHTER_KIND_ELIGHT),
        ("falco", *FIGHTER_KIND_FALCO),
        ("fox", *FIGHTER_KIND_FOX),
        ("gamewatch", *FIGHTER_KIND_GAMEWATCH),
        ("ganon", *FIGHTER_KIND_GANON),
        ("gaogaen", *FIGHTER_KIND_GAOGAEN),
        ("gekkouga", *FIGHTER_KIND_GEKKOUGA),
        ("ike", *FIGHTER_KIND_IKE),
        ("inkling", *FIGHTER_KIND_INKLING),
        ("jack", *FIGHTER_KIND_JACK),
        ("kamui", *FIGHTER_KIND_KAMUI),
        ("ken", *FIGHTER_KIND_KEN),
        ("kirby", *FIGHTER_KIND_KIRBY),
        ("koopa", *FIGHTER_KIND_KOOPA),
        ("koopajr", *FIGHTER_KIND_KOOPAJR),
        ("krool", *FIGHTER_KIND_KROOL),
        ("link", *FIGHTER_KIND_LINK),
        ("littlemac", *FIGHTER_KIND_LITTLEMAC),
        ("lucario", *FIGHTER_KIND_LUCARIO),
        ("lucas", *FIGHTER_KIND_LUCAS),
        ("lucina", *FIGHTER_KIND_LUCINA),
        ("luigi", *FIGHTER_KIND_LUIGI),
        ("mario", *FIGHTER_KIND_MARIO),
        ("mariod", *FIGHTER_KIND_MARIOD),
        ("marth", *FIGHTER_KIND_MARTH),
        ("master", *FIGHTER_KIND_MASTER),
        ("metaknight", *FIGHTER_KIND_METAKNIGHT),
        ("mewtwo", *FIGHTER_KIND_MEWTWO),
        ("murabito", *FIGHTER_KIND_MURABITO),
        ("ness", *FIGHTER_KIND_NESS),
        ("packun", *FIGHTER_KIND_PACKUN),
        ("pacman", *FIGHTER_KIND_PACMAN),
        ("palutena", *FIGHTER_KIND_PALUTENA),
        ("peach", *FIGHTER_KIND_PEACH),
        ("pfushigisou", *FIGHTER_KIND_PFUSHIGISOU),
        ("pichu", *FIGHTER_KIND_PICHU),
        ("pickel", *FIGHTER_KIND_PICKEL),
        ("pikachu", *FIGHTER_KIND_PIKACHU),
        ("pikmin", *FIGHTER_KIND_PIKMIN),
        ("pit", *FIGHTER_KIND_PIT),
        ("pitb", *FIGHTER_KIND_PITB),
        ("plizardon", *FIGHTER_KIND_PLIZARDON),
        ("popo", *FIGHTER_KIND_POPO),
        ("purin", *FIGHTER_KIND_PURIN),
        ("pzenigame", *FIGHTER_KIND_PZENIGAME),
        ("reflet", *FIGHTER_KIND_REFLET),
        ("richter", *FIGHTER_KIND_RICHTER),
        ("ridley", *FIGHTER_KIND_RIDLEY),
        ("robot", *FIGHTER_KIND_ROBOT),
        ("rockman", *FIGHTER_KIND_ROCKMAN),
        ("rosetta", *FIGHTER_KIND_ROSETTA),
        ("roy", *FIGHTER_KIND_ROY),
        ("ryu", *FIGHTER_KIND_RYU),
        ("samus", *FIGHTER_KIND_SAMUS),
        ("samusd", *FIGHTER_KIND_SAMUSD),
        ("sheik", *FIGHTER_KIND_SHEIK),
        ("shizue", *FIGHTER_KIND_SHIZUE),
        ("shulk", *FIGHTER_KIND_SHULK),
        ("simon", *FIGHTER_KIND_SIMON),
        ("snake", *FIGHTER_KIND_SNAKE),
        ("sonic", *FIGHTER_KIND_SONIC),
        ("szerosuit", *FIGHTER_KIND_SZEROSUIT),
        ("tantan", *FIGHTER_KIND_TANTAN),
        ("toonlink", *FIGHTER_KIND_TOONLINK),
        ("trail", *FIGHTER_KIND_TRAIL),
        ("wario", *FIGHTER_KIND_WARIO),
        ("wiifit", *FIGHTER_KIND_WIIFIT),
        ("wolf", *FIGHTER_KIND_WOLF),
        ("yoshi", *FIGHTER_KIND_YOSHI),
        ("younglink", *FIGHTER_KIND_YOUNGLINK),
        ("zelda", *FIGHTER_KIND_ZELDA),
    ];
    pairs.iter().map(|&(folder, kind)| (kind, folder)).collect()
});

const KNOWN_ADDED_CHARACTERS: [&str; 4] = ["toad", "peppy", "bomberman", "rayman"];

fn foreign_marked_slots(kind: i32) -> Vec<i32> {
    let Some(&folder) = KIND_TO_FOLDER.get(&kind) else {
        return Vec::new();
    };
    let mut known = KNOWN_ADDED_CHARACTERS.to_vec();
    known.push(folder);
    crate::util::REGISTRY
        .get_unrecognized_marked_costumes(folder, &known)
        .into_iter()
        .map(|s| s as i32)
        .collect()
}

fn apply_multiplier_to_all_kinds(default_slots: Vec<i32>, type_hash: u64, name_hash: u64, multiplier: f32) {
    let default_slots: Vec<i32> = if default_slots.contains(&-1) {
        (0..=256).collect()
    } else {
        default_slots
    };

    let own_by_kind: HashMap<i32, (Vec<i32>, ParamValue)> = BASELINES.lock().iter()
        .filter(|((kind, _, th, nh), _)| *kind != *FIGHTER_KIND_ALL && *th == type_hash && *nh == name_hash)
        .map(|((kind, slots, _, _), value)| (*kind, (slots.clone(), *value)))
        .collect();

    for kind in (*FIGHTER_KIND_BASE_HEAD)..=(*FIGHTER_KIND_BASE_APPEND_TAIL) {
        let foreign = foreign_marked_slots(kind);

        let remaining_slots: Vec<i32> = if let Some((own_slots, value)) = own_by_kind.get(&kind) {
            match value {
                ParamValue::Float(base) => {
                    let new_value = base * multiplier;
                    BASELINES.lock().insert((kind, own_slots.clone(), type_hash, name_hash), ParamValue::Float(new_value));
                    param_config::update_float_2(kind, own_slots.clone(), (type_hash, name_hash, new_value));
                }
                ParamValue::Int(base) => {
                    let new_value = (*base as f32 * multiplier).round() as i32;
                    BASELINES.lock().insert((kind, own_slots.clone(), type_hash, name_hash), ParamValue::Int(new_value));
                    param_config::update_int_2(kind, own_slots.clone(), (type_hash, name_hash, new_value));
                }
            }
            default_slots.iter().copied().filter(|s| !own_slots.contains(s) && !foreign.contains(s)).collect()
        } else {
            default_slots.iter().copied().filter(|s| !foreign.contains(s)).collect()
        };

        if !remaining_slots.is_empty() {
            param_config::update_attribute_mul_2(kind, remaining_slots, (type_hash, name_hash, multiplier));
        }
    }
}
