
[general]
sh_macro = 0
hold_buffer = 0
hitstun = 0
hitlag = 2
ledges = 1
respawn_anim = 1

[movement]
dash = 0
moonwalk = 0
pivots = 0
llpc = 1
jump_accel = 0
hitfall = 1
agt = 1
djc = 0
footstool = 2
edge_cancel = 0
jump_cancel = 0
g2a = 0

[attacks]
jab_cancel = 0
dacus = 0
ac = 1
jcg = 1
grab = 1
lcancel = 0
special_cancel = 0

[defense]
shield = 1
shield_health = 0
shieldstun = 0
airdodge = 0
shield_drop = 0
di = 0
no_tumble_di = 0
drift_di = 1
hitstun_cancel = 2
vertical_gravity = 2

[stats]
ll = 5
initial_dash = 1
runspeed = 0
walkspeed = 0
airspeed = 1
airaccel = 6
traction = 4
fallspeed = 2
jump = 0
gravity = 2
weight = 0

[special]
cancel_to_taunt = 0
parry_reflect = 0
taunt_cancel = 0
no_special_fall = 1
random_trip = 0
