#![feature(concat_idents)]
#![feature(proc_macro_hygiene)]
#![feature(asm)]
#![allow(unused_imports)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(non_upper_case_globals)]
#![allow(warnings, unused)]

pub static mut FIGHTER_MANAGER: usize = 0;

mod util;
mod hooks;
mod doc;
mod faf_change;
mod yink;
mod sora;
mod kazuya;
mod peach;
mod rosa;
mod brawler;
mod pacman;
mod swordfighter;
mod jr;
mod incin;
mod mario;
mod link;
mod samusd;
mod samus;
mod kirby;
mod isa;
mod plant;
mod banjo;
mod fox;
mod marth;
mod ics;
mod pika;
mod bayo;
mod villy;
mod pt;
mod wft;
mod joker;
mod richter;
mod ridley;
mod inkling;
mod cloud;
mod terry;
mod chrom;
mod mac;
mod gren;
mod palu;
mod mewtwo;
mod d3;
mod gnw;
mod ike;
mod sonic;
mod byleth;
mod diddy;
mod dpit;
mod gunner;
mod zss;
mod lucario;
mod command;
mod robin;
mod sephiroth;
mod ryu;
mod dh;
mod luigi;
mod puff;
mod mk;
mod sheik;
mod zelda;
mod pichu;
mod falco; 
mod bowser;
mod ganon;
mod wolf;
mod lucina;
mod pit;
mod tink;
mod wario;
mod lucas;
mod rob;
mod oli;
mod minmin;
mod hero;
mod falcon;
mod corrin;
mod roy;
mod krool;
mod remove_quake;
mod mythra;
mod dk;
mod simon;
mod projectile_invuln;

#[skyline::main(name = "ult_s")]
pub fn main() {
	util::install();
	hooks::install();
	faf_change::install();
	dk::install();
	peach::install();
	mythra::install();
	yink::install();
	sora::install();
    brawler::install();
	falcon::install();
	swordfighter::install();
	mario::install();
	link::install();
	samusd::install();
	samus::install();
	wft::install();
	roy::install();
	pacman::install();
	kirby::install();
	doc::install();
	plant::install();
	kazuya::install();
	banjo::install();
	fox::install();
	marth::install();
	simon::install();
	bayo::install();
	villy::install();
	richter::install();
	isa::install();
	ridley::install();
	inkling::install();
	cloud::install();
	terry::install();
	chrom::install();
	mac::install();
	gren::install();
	palu::install();
	mewtwo::install();
	d3::install();
	gnw::install();
	ike::install();
	sonic::install();
	diddy::install();
	dpit::install();
	gunner::install();
	zss::install();
	lucario::install();
	sephiroth::install();
	ryu::install();
	dh::install();
	luigi::install();
	puff::install();
	mk::install();
	sheik::install();
	zelda::install();
	pichu::install();
	falco::install();
	bowser::install();
	ganon::install();
	wolf::install();
	lucina::install();
	pit::install();
	pika::install();
	tink::install();
	wario::install();
	lucas::install();
	rob::install();
	byleth::install();
	minmin::install();
	jr::install();
	hero::install();
	command::install();
	robin::install();
	rosa::install();
	oli::install();
	pt::install();
	joker::install();
	ics::install();
	incin::install();
	corrin::install();
	krool::install();
	remove_quake::install();
	projectile_invuln::install();
}